# ==========================================
# 🚀 CUSTOM TAB SHORTCUTS (No Prefix Needed)
# ==========================================

# Alt + 1 அழுத்தினால் -> Ranger (Pane 0) திறக்க
bind -n M-1 select-pane -t 0

# Alt + 2 அழுத்தினால் -> Nano (Pane 1) திறக்க
bind -n M-2 select-pane -t 1

# Alt + 3 அழுத்தினால் -> Terminal (Pane 2) திறக்க
bind -n M-3 select-pane -t 2

# Alt + 4 -> Session-a kill panni exit aaga
bind -n M-4 kill-session -t archide
