# ==========================================
# 🚀 CUSTOM TAB SHORTCUTS (No Prefix Needed)
# ==========================================

# Alt + 1, 2, 3 (நேற்று கச்சிதமாக வேலை செய்த கோட்)
bind -n M-1 select-pane -t 0
bind -n M-2 select-pane -t 1
bind -n M-3 select-pane -t 2

# Fn + 4 (F4) மூலம் செஷனை க்ளோஸ் செய்ய
bind -n F4 kill-session -t archide
