# ==========================================
# 🚀 CUSTOM TAB SHORTCUTS (No Prefix Needed)
# ==========================================

# Super (Windows key) + எண் பயன்படுத்தி பேன்களை மாற்ற
bind -n M4+1 select-pane -t 0
bind -n M4+2 select-pane -t 1
bind -n M4+3 select-pane -t 2

# Alt + 4 -> Session-a kill panni exit aaga
bind -n M4+4 kill-session -t archide
